name=BTS7960
version=1.0.1
author=Luis Llamas
maintainer=Axel Sepulveda
sentence=Library for BTS7960 Dual H-Bridge 43A
paragraph=Library for BTS7960 Dual H-Bridge 43A
category=Device Control
url=https://github.com/chepo92/Arduino-BTS7960
architectures=*
